name: Tesla Deaths
run-name: Production Deployment
on:
  create: 
    tags:
      - v*
    branches:
      - main

jobs:
  docker_build:
    environment:
        name: test
    env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}    
    
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install --upgrade pip && pip install pipenv && pipenv install --system --deploy --ignore-pipfile --dev

    - name: Login Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tesla_deaths:${{ github.ref_name }}
  
  deploy:
    environment:
        name: test
    env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}    
    
    runs-on: ubuntu-22.04
    
    steps:
      - name: Deploy versioned image in EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.SSH_KEY }}
            fingerprint: 
            script: |
                docker rm -f tesla_deaths || true
                echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin 
                docker pull ${DOCKERHUB_USERNAME}/tesla_deaths:${{ github.ref_name }}
                docker run -d --name tesla_deaths --network appnetwork -p 8501:8501 ${DOCKERHUB_USERNAME}/tesla_deaths:${{ github.ref_name }}
  